### ISSUE TITLE
How do I execute raw sql inside my report?

### ISSUE THREAD

**Issue by ftrotter** [CareSet/CareSetReportEngine#10]
Frequently, we need to run "setup queries" before we actually run the report in GetSQL...

How do we do that in a way that does not break the query caching system completely?

Can we set it up so that some reports have to be run every time, without using the query? 

Can we set it up so that if the GetSQL is doing preparatory work each time, that the engine knows that it cannot cache the  #result?

Should we have a PrepSQL() function that separates this process out? So that the engine can know "the results of the preparation are different, therefore the GetSQL results will be different, therefore I cannot use the cache?"

-FT

**Comment by siphu** [comment]
Any sql statement can be ran through the GetSQL()
it will only insert SELECT statement into the cache table.
any CREATE TABLE,UPDATE TABLE,INSERT INTO will be ran, but will not be cache.

alternatively, laravel DB:: command will still work

**Comment by ftrotter** [comment]
Interesting but not what I am asking. 

What I need to know how to do is make a query, and use the results to build the SQL that will become the SQL query that I pass back as the result of GetSQL.
