### ISSUE TITLE
Only show paging when paging is needed

### ISSUE THREAD

**Issue by ftrotter** [CareSet/CareSetReportEngine#11]
No need to select whether to see 50, 100 or 1000 on one page, when there are only 7 results.

Similarly, there is no reason to have the "previous, 1, next' box when there is no second page.

**Comment by siphu** [comment]
This is a functionality of datatables and not through the caresetreportengine

**Comment by siphu** [comment]
to get this to work, it would require more work to the datatables,
the tabular view is an example on how to use the datatables with the data
