### ISSUE TITLE
Globally enable/disable caching

### ISSUE THREAD

**Issue by ftrotter** [CareSet/CareSetReportEngine#15]
There should be an option to turn off caching for the entire system at the configuration level.

**Comment by siphu** [comment]
global caching can be enable/disabled via the caresetreportengine.php config file -

**
     * Make the cache table presistent. If this value is set to false, The a TEMPORARY table will be used instead
     */
    'CACHABLE' =>env("REPORT_CACHABLE",true),
    /**
     * How old is the cache table before we need to override it.
     * In Minutes.
     * 0 = no timeout
     */
    'CACHE_TIMEOUT' =>env("REPORT_TIMEOUT", 0),

**Comment by ftrotter** [comment]
improved comments to reflect that this variable turns on and off caching
