### ISSUE TITLE
Remember the number of entries to display 

### ISSUE THREAD

**Issue by ftrotter** [CareSet/CareSetReportEngine#19]
across reports. So if I say "show me 1000" keep that as the setting as I change reports..

Perhaps each report should be able to enforce a starting default entries? So that a report that would be crippled by showing 1000 can avoid that by having a setting that forces only 10 (or whatever, to be shown?) 

But for now, lets just remember what the setting was and respect it. KISS

**Comment by siphu** [comment]
duplicate ticket
