### ISSUE TITLE
Remember more entries option choice

### ISSUE THREAD

**Issue by ftrotter** [CareSet/CareSetReportEngine#23]
I keep having to choose 1000 over and over and over again... 

When I choose a number it should remember it on all reports...

At least if that choice is anything less than "All"... I think it is reasonable to have to manually request each new report to give you all the results...

**Comment by ftrotter** [comment]
I regard this as a high-priority bug. However, since it does not make sense for you to develop this on the front end until the backend has matured somewhat, I am downgrading the priority.

**Comment by siphu** [comment]
default paging length has increased, the report will default to the last one it remembered
