### ISSUE TITLE
Document clearly how url + request information is passed into GetSQL

### ISSUE THREAD

**Issue by ftrotter** [CareSet/CareSetReportEngine#5]
Apparently getCode() will get the first URI component. 

Apparently getParameters() will get the rest of the URI component. 

How do I get JSON variables? How do I get _GET variables? Do I use the Laravel request object? Does that live on the report object somewhere? 

All of this should be documented in both the how-to and the sourcecode of the generated files.

**Comment by siphu** [comment]
duplicate ticket #6
